services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./media:/app/media
      - ./db.sqlite3:/app/db.sqlite3
    environment:
      - DEBUG=True
    command: python manage.py runserver 0.0.0.0:8000